### ISSUE TITLE
RTE Segfault: To many variables questioned in one FBSheet in CSHMI

### ISSUE THREAD

**Issue by JGrothoff** [acplt/rte#46]
Hi together.

If i open a FBSheet in CSHMI in my browser (firefox) and there are around 20 to 30 Functioncharts with 10 inputs and 10 outputs each, i will get a segfault for the server, that hosts the functionblocks. So i guess there is a limit, that is not catched correctly.
Bad news is, that if i leave the browser window open, the site won't stop asking for the variables. So i can't start the server, as it will have the segfault after startup again.

> Thread #1 [ov_runtimeserve] 4440 [core: 3] (Suspended : Signal : SIGSEGV:Segmentation fault)	
	ov_element_searchchild() at ov_element.c:62 0x7ffff7ba443a	
	ov_path_resolve() at ov_path.c:371 0x7ffff7bb0152	
	ov_ksserver_getvar() at ovks_backend_getvar.c:94 0x7ffff73b9b3d	
	kshttp_exec_getvar() at service_getvar.c:115 0x7ffff6335e18	
	kshttp_httpclienthandler_generateHttpBody() at httpclienthandler.c:217 0x7ffff632791a	
	kshttp_httpclienthandler_HandleRequest() at httpclienthandler.c:79 0x7ffff6327160	
	TCPbind_TCPChannel_typemethod() at TCPChannel.c:543 0x7ffff7198faf	
	ksbase_RootComTask_execute() at RootComTask.c:250 0x7ffff73b3ea3	
	ov_scheduler_schedulenextevent() at ov_scheduler.c:259 0x7ffff7bc4884	
	ov_ksserver_stripped_run() at ov_runtimeserver.c:205 0x401f59	
	<...more frames...>	

How to reproduce the error:
1. Load CSHMI templates
2. Load Bug_ToManyVariablesForCSHMI-10.fbd to Bug_ToManyVariablesForCSHMI-30.fbd
	Each FBD has 10 empty functioncharts with 10 inputs and 10 outputs each.
3. open csHMI FBSheet on .../TechUnits/BugTest

[Bug_ToManyVariablesForCSHMI-10.txt](https://github.com/acplt/rte/files/1946717/Bug_ToManyVariablesForCSHMI-10.txt)
[Bug_ToManyVariablesForCSHMI-20.txt](https://github.com/acplt/rte/files/1946718/Bug_ToManyVariablesForCSHMI-20.txt)
[Bug_ToManyVariablesForCSHMI-30.txt](https://github.com/acplt/rte/files/1946719/Bug_ToManyVariablesForCSHMI-30.txt)

**Comment by JGrothoff** [comment]
Thanks to @LarsNt, we found the error. The KS getvar request from csHMI is bigger than the OV_MEMSTACK_SIZE of a memstack page.
In consequence the memory is overwritten in:
https://github.com/acplt/rte/blob/master/syslibs/comm/kshttp/source/service_getvar.c#L109
We will change the memstack implementation to allocate the needed memory in:
https://github.com/acplt/rte/blob/master/core/ov/source/libov/ov_memstack.c#L124

**Comment by LarsNt** [comment]
On closer inspection the memstack already supports arbitrary large pages [ov_memstack.c L125](https://github.com/acplt/rte/blob/master/core/ov/source/libov/ov_memstack.c#L125).

The problem lies in the usage of the allocated memory.
In [service_getvar.c L94](https://github.com/acplt/rte/blob/master/syslibs/comm/kshttp/source/service_getvar.c#L94) the right amount of memory is allocated in *addrp. But this pointer is overwritten in [L107](https://github.com/acplt/rte/blob/master/syslibs/comm/kshttp/source/service_getvar.c#L107). Furthermore, the loop in [L106](https://github.com/acplt/rte/blob/master/syslibs/comm/kshttp/source/service_getvar.c#L106) increases the pointer addrp which is only allocated as a single pointer in [L92](https://github.com/acplt/rte/blob/master/syslibs/comm/kshttp/source/service_getvar.c#L92).
As the memstack page is almost empty at this point most requests will not cause any problems. 64 bit systems are more likely to suffer from this issue since the pointer size is doubled compared to 32 bit systems.
Further instances of this bug may exist e.g. [service_setvar.c](https://github.com/acplt/rte/blob/master/syslibs/comm/kshttp/source/service_setvar.c).

**Comment by HolgerJeromin** [comment]
> Furthermore, the loop in L106 increases the pointer addrp which is only allocated as a single pointer in L92.

OV_STRING is a pointer. OV_STRING* is therefor an array of pointers.

**Comment by JGrothoff** [comment]
@LarsNt [commit](https://github.com/acplt/rte/commit/9a2b95b31818baa84bb7d273e705a38f75f0aa00) seems to fix it.

**Comment by FlorianPalm** [comment]
That seems to be the problem:
![grafik](https://user-images.githubusercontent.com/6229099/39805811-2526052c-5378-11e8-8768-6c250ee686a4.png)

**Comment by HolgerJeromin** [comment]
@FlorianPalm is that powerpoint or a fancy tool?

**Comment by FlorianPalm** [comment]
:smiley:  just ppt
